### ISSUE TITLE
Question about "open_src_model_T2T_generation.py".

### ISSUE THREAD

**Issue by JamesJang26** [yale-nlp/LLM-T2T#3]
Hello, 

I'm keep looking with your great research and have another question again.

When I look down into "open_src_model_T2T_generation.py", while setting 'data_path', no paths are getting allocated into data_path variable. I see no 'LOGICNLG_PATH', 'FETAQA_PATH', ... and so on.

I'm quite not good at reviewing code, so even if my question is simple or weird, forgive me. lol

Thank you

**Comment by dongsukjang26** [comment]
One more question for the direct inference, using open source LLM. It keeps stopping generation in 10/500 iterations. Below is my result from terminal.

"""
$ python src/open_src_model_T2T_generation.py \
    --model_type llama-13b \
    --model_name_or_path huggyllama/llama-13b \
    --mode direct \
    --direct CoT \
    --dataset FeTaQA \
    --output_path output/FeTaQA \
> 
tokenizer_config.json: 100%|████████████████████| 700/700 [00:00<00:00, 118kB/s]
tokenizer.model: 100%|████████████████████████| 500k/500k [00:00<00:00, 646kB/s]
tokenizer.json: 100%|██████████████████████| 1.84M/1.84M [00:00<00:00, 1.86MB/s]
special_tokens_map.json: 100%|██████████████████| 411/411 [00:00<00:00, 219kB/s]
config.json: 100%|██████████████████████████████| 595/595 [00:00<00:00, 105kB/s]
model.safetensors.index.json: 100%|████████| 33.4k/33.4k [00:00<00:00, 5.50MB/s]
model-00001-of-00003.safetensors: 100%|████| 9.95G/9.95G [14:19<00:00, 11.6MB/s]
model-00002-of-00003.safetensors: 100%|████| 9.90G/9.90G [14:16<00:00, 11.6MB/s]
model-00003-of-00003.safetensors: 100%|████| 6.18G/6.18G [08:55<00:00, 11.5MB/s]
Downloading shards: 100%|████████████████████████| 3/3 [37:35<00:00, 751.99s/it]

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/james/anaconda3/envs/llm-t2t/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/james/anaconda3/envs/llm-t2t/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/james/anaconda3/envs/llm-t2t/lib/libcudart.so'), PosixPath('/home/james/anaconda3/envs/llm-t2t/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /home/james/anaconda3/envs/llm-t2t/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /home/james/anaconda3/envs/llm-t2t/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
Loading checkpoint shards: 100%|██████████████████| 3/3 [00:05<00:00,  1.71s/it]
generation_config.json: 100%|██████████████████| 137/137 [00:00<00:00, 22.2kB/s]
  2%|▊                                       | 10/500 [05:53<4:48:23, 35.31s/it]
"""

Would really appreciate if you help with my problem. Thank you.

**Comment by yilunzhao** [comment]
Hi @JamesJang26, thanks for your interests in our work!

> When I look down into "open_src_model_T2T_generation.py", while setting 'data_path', no paths are getting allocated into data_path variable. I see no 'LOGICNLG_PATH', 'FETAQA_PATH', ... and so on.

These paths are defined at `utils.constants`. 

> It keeps stopping generation in 10/500 iterations. Below is my result from terminal.

Thank you for bringing this issue to our attention. The stopping at 10 iterations occurs because the default value of [`--num_limit`](https://github.com/yale-nlp/LLM-T2T/blob/bb1137e4a59dcb700bee0b2af9a61ab2beb6d8bd/src/open_src_model_T2T_generation.py#L94) is set to 10. For real experiments, this should be explicitly set to 500. 

We have updated the README to reflect this information more clearly.
